#!/usr/bin/env bash
set -euo pipefail -x
#####################################
#           Git hook file           #
# https://git-scm.com/docs/githooks #
#####################################

export PATH="node_modules/.bin:${PATH}"

lint-staged --verbose
