name: Check

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'assets/**'
      - '.github/**'
      - '!.github/workflows/check.yml'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'assets/**'
      - '.github/**'
      - '!.github/workflows/check.yml'

  workflow_dispatch:
  workflow_call:

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
